<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="RabbitMQ.Client" Version="7.2.2" />
    <PackageVersion Include="Confluent.Kafka" Version="2.15.1" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
</Project>
