<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>PriceSeeder</AssemblyName>
    <RootNamespace>PriceSeeder</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\SimpleEventing\SimpleEventing.csproj" />
  </ItemGroup>
</Project>
