<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Receiver</AssemblyName>
    <RootNamespace>Receiver</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\SimpleMessaging\SimpleMessaging.csproj" />
  </ItemGroup>
</Project>
