version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq
    restart: on-failure

volumes:
  rabbitmq-home:
    driver: local
