<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>StreamConsumer</AssemblyName>
    <RootNamespace>StreamConsumer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\SimpleEventing\SimpleEventing.csproj" />
  </ItemGroup>
</Project>
